---
title: "Appendix"
author: "Isabel Renteria and Zuzu Trottier"
editor_options:
  chunk_output_type: inline
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r, include=FALSE}
# read in data
raw_1516 <- read.csv("~/stat_proj_1/data/Y1516.csv", header = T)
raw_1617 <- read.csv("~/stat_proj_1/data/Y1617.csv", header = T)
raw_1718 <- read.csv("~/stat_proj_1/data/Y1718.csv", header = T)
raw_1819 <- read.csv("~/stat_proj_1/data/Y1819.csv", header = T)
raw_2122 <- read.csv("~/stat_proj_1/data/Y2122.csv", header = T)
raw_2223 <- read.csv("~/stat_proj_1/data/Y2223.csv", header = T)

# filter data for the attendance and suspension columns
library(tidyverse)

num_filtered_1516 <- raw_1516 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

num_filtered_1617 <- raw_1617 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

num_filtered_1718 <- raw_1718 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

num_filtered_1819 <- raw_1819 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

num_filtered_2122 <- raw_2122 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

num_filtered_2223 <- raw_2223 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) %>%
  na.omit()

```

```{r, include=FALSE}
pre_covid_num <- rbind(num_filtered_1516,num_filtered_1617,num_filtered_1718,num_filtered_1819)
post_covid_num <- rbind(num_filtered_2122,num_filtered_2223)

all_data <- rbind(pre_covid_num,post_covid_num)
```

```{r, include=T}
cor(pre_covid_num)
cor(post_covid_num)
# generally independent, with some higher correlation values for (suspensions and 
# student attendance) and (suspensions and misconduct-to-suspensions)
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Multivariate QQ plot for pre covid data"}
library(MVN)
# QQ plot
mvn_pre <- mvn(pre_covid_num, mvnTest="hz", multivariatePlot = "qq") #no
```


```{r, echo=T, fig.width=4,fig.height=4, fig.align='center', fig.cap="Multivariate QQ plot for pre covid data"}
# MVN
mvn_pre$multivariateNormality
```

```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Multivariate QQ plot for post covid data"}
# QQ plot
mvn_post <- mvn(post_covid_num, mvnTest="hz" , multivariatePlot = "qq") #no
```


```{r, echo=T, fig.width=4,fig.height=3, fig.align='center', fig.cap="Multivariate QQ plot for post covid data"}
# MVN
mvn_post$multivariateNormality
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Multivariate QQ plot for all data"}
# QQ plot
mvn_all <- mvn(all_data, mvnTest="hz" , multivariatePlot = "qq") #no
```


```{r, include=F}
library(factoextra)
library(broom)
```


```{r, include=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for pre covid data's PCA"}
#PC selection
PCA_pre <- prcomp(pre_covid_num)
prop_pre <- sum(PCA_pre$sdev[1:2])/sum(PCA_pre$sdev) # 86.4%
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for pre covid data's PCA"}
#Biplot
fviz_pca_var(PCA_pre,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r, include=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for post covid data's PCA"}
# PC selection
PCA_post <- prcomp(post_covid_num)
prop_post <- sum(PCA_post$sdev[1:2])/sum(PCA_post$sdev) # 84.0%
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for post covid data's PCA"}
# Biplot
fviz_pca_var(PCA_post,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```


```{r, include=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for all data's PCA"}
# PC selection
PCA_all <- prcomp(all_data)
prop_all <- sum(PCA_all$sdev[1:2])/sum(PCA_all$sdev) # 83.6%
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for all data's PCA"}
# Biplot
fviz_pca_var(PCA_all,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r, echo=T, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for pre covid data's PCA when scaled by standard deviation"}
# PC selection
PCA_pre <- prcomp(pre_covid_num, scale = sapply(pre_covid_num,sd))
summary(PCA_pre)
```


```{r, echo=F, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for pre covid data's PCA when scaled by standard deviation"}
# Biplot
fviz_pca_var(PCA_pre,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r, echo=T, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for post covid data's PCA when scaled by standard deviation"}
# PC selection
PCA_post <- prcomp(post_covid_num, scale = sapply(post_covid_num,sd))
summary(PCA_post)
```


```{r, echo=FALSE, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for post covid data's PCA when scaled by standard deviation"}
fviz_pca_var(PCA_post,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```

```{r, echo=T, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for all data's PCA when scaled by standard deviation"}
# PC selection
PCA_all <- prcomp(all_data, scale = sapply(all_data,sd))
summary(PCA_all)
```


```{r, echo=FALSE, fig.width=4,fig.height=4, fig.align='center', fig.cap="Biplot of variables for all data's PCA when scaled by standard deviation"}
fviz_pca_var(PCA_all,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )

# need to use another PC to get the same level of varability explained when not scaled by sd
```

```{r, include=FALSE, fig.width=4,fig.height=4, fig.align='center'}
manova_1516 <- raw_1516 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit()

manova_1617 <- raw_1617 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

manova_1718 <- raw_1718 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

manova_1819 <- raw_1819 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

manova_2122 <- raw_2122 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

manova_2223 <- raw_2223 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

box_pre <- rbind(manova_1516,manova_1617,manova_1718,manova_1819)
box_post <- rbind(manova_2122,manova_2223)

```

```{r, include=T}
# MANOVA with Wilks-Lambda test for pre covid data
mano_pre_PC <- manova( cbind(Suspensions_Per_100_Students_Year_2_Pct,
                             Misconducts_To_Suspensions_Year_2_Pct,
                             Teacher_Attendance_Year_2_Pct,
                             Student_Attendance_Year_2_Pct) 
                       ~Primary_Category , data = box_pre)
summary(mano_pre_PC, test="Wilks")

# MANOVA with Wilks-Lambda test for post covid data
mano_post_PC <- manova( cbind(Suspensions_Per_100_Students_Year_2_Pct,
                              Misconducts_To_Suspensions_Year_2_Pct,
                              Teacher_Attendance_Year_2_Pct,
                              Student_Attendance_Year_2_Pct) 
                        ~Primary_Category , data = box_post)
summary(mano_post_PC, test="Wilks")

```

```{r, include=T}
#pre ANOVAs
summary.aov(mano_pre_PC)
#post ANOVAs
summary.aov(mano_post_PC)
```

```{r, include=F}
library(gridExtra)
library(ggplot2)
```


```{r, include=T}
#pre box plot
box_ta_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Teacher_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sa_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Student_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sus_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Suspensions_Per_100_Students_Year_2_Pct)) +
  geom_boxplot() 
box_mis_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Misconducts_To_Suspensions_Year_2_Pct)) +
  geom_boxplot()

#post box plot
box_ta_post <- ggplot(box_post, aes(x = Primary_Category, y = Teacher_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sa_post <- ggplot(box_post, aes(x = Primary_Category, y = Student_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sus_post <- ggplot(box_post, aes(x = Primary_Category, y = Suspensions_Per_100_Students_Year_2_Pct)) +
  geom_boxplot() 
box_mis_post <- ggplot(box_post, aes(x = Primary_Category, y = Misconducts_To_Suspensions_Year_2_Pct)) +
  geom_boxplot()
```


```{r, fig.width=6,fig.height=4, echo=FALSE, fig.align='center', fig.cap="Box Plots of Student Attendance with pre covid on the left and post covid on the right"}
grid.arrange(box_sa_pre,box_sa_post, nrow=1)
```

```{r, fig.width=6,fig.height=4, echo=FALSE, fig.align='center',fig.cap="Box Plots of Teacher Attendance with pre covid on the left and post covid on the right"}
grid.arrange(box_ta_pre,box_ta_post, nrow=1)
```

```{r, fig.width=6,fig.height=4, echo=FALSE, fig.align='center', fig.cap="Box Plots of Suspensions with pre covid on the left and post covid on the right"}
grid.arrange(box_sus_pre,box_sus_post, nrow=1)
```

```{r, fig.width=6,fig.height=4, echo=FALSE, fig.align='center',fig.cap="Box Plots of misconducts to suspensions with pre covid on the left and post covid on the right"}
grid.arrange(box_mis_pre,box_mis_post,nrow=1)
```

