---
title: "Project 1"
author: "Isabel Renteria and Zuzu Trottier"
editor_options: 
  chunk_output_type: inline
---

#filtering data
```{r}
# read in data
raw_1516 <- read.csv("~/stat_proj_1/data/Y1516.csv", header = T)
raw_1617 <- read.csv("~/stat_proj_1/data/Y1617.csv", header = T)
raw_1718 <- read.csv("~/stat_proj_1/data/Y1718.csv", header = T)
raw_1819 <- read.csv("~/stat_proj_1/data/Y1819.csv", header = T)
raw_2122 <- read.csv("~/stat_proj_1/data/Y2122.csv", header = T)
raw_2223 <- read.csv("~/stat_proj_1/data/Y2223.csv", header = T)

# filter data for the attendance and suspension columns
library(tidyverse)

manova_1516 <- raw_1516 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>% 
  na.omit()

manova_1617 <- raw_1617 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>% 
  na.omit()

manova_1718 <- raw_1718 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>% 
  na.omit()

manova_1819 <- raw_1819 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>% 
  na.omit()

manova_2122 <- raw_2122 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>%
  na.omit()

manova_2223 <- raw_2223 %>% 
  select(contains("Attendance") | 
         contains("Suspensions") |
         "Primary_Category") %>%
  select(ends_with("2_Pct")) %>%
  select(!contains("Avg")) %>%
  select(!contains("Lbl")) %>%
  select(!contains("PSAT")) %>% 
  na.omit()

```

# our different considerations of groupings
```{r}
pre_covid_mano <- rbind(manova_1516,manova_1617,manova_1718,manova_1819)
post_covid_mano <- rbind(manova_2122,manova_2223)



pre_covid_mano <- mutate(pre_covid_mano, across(everything(), ~ ifelse(.x == 0, 0.01, .x)))
post_covid_mano <- mutate(post_covid_mano, across(everything(), ~ ifelse(.x == 0, 0.01, .x)))

all_data <- rbind(pre_covid_mano,post_covid_mano)
```

# Independent?
```{r}
cor(pre_covid_mano)
cor(post_covid_mano)
cor(all_data)
# generally independent, with some higher correlation values for (suspensions and student attendance) and (suspensions and misconduct-to-suspensions)
```

# Normality?
```{r}
mvn(post_covid_mano, mvnTest="hz", multivariatePlot = "qq") #no
mvn(pre_covid_mano, mvnTest="hz" , multivariatePlot = "qq") #no
mvn(all_data, mvnTest="hz" , multivariatePlot = "qq") #no
```

#MANOVA
```{r}
mano_pre <- manova( cbind(Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) ~ Student_Attendance_Year_2_Pct, data = pre_covid_mano)
summary(mano_pre)

mano_post <- manova( cbind(Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) ~ Student_Attendance_Year_2_Pct, data = post_covid_mano)
summary(mano_post)

mano_all <- manova( cbind(Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct) ~ Student_Attendance_Year_2_Pct, data = all_data)
summary(mano_all, test = "Wilks")
```
#PCA
```{r}
PCA_pre <- prcomp(pre_covid_mano)
prop_pre <- sum(PCA_pre$sdev[1:2])/sum(PCA_pre$sdev) # 86.4%
fviz_pca_var(PCA_pre,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
PCA_post <- prcomp(post_covid_mano)
prop_post <- sum(PCA_post$sdev[1:2])/sum(PCA_post$sdev) # 84.0%
fviz_pca_var(PCA_post,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
PCA_all <- prcomp(all_data)
prop_all <- sum(PCA_all$sdev[1:2])/sum(PCA_all$sdev) # 83.6%
fviz_pca_var(PCA_all,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
```
#PCA if scaled by sd
```{r}
PCA_pre <- prcomp(pre_covid_mano, scale = sapply(pre_covid_mano,sd))
prop_pre <- sum(PCA_pre$sdev[1:3])/sum(PCA_pre$sdev) # 84.1%
fviz_pca_var(PCA_pre,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
PCA_post <- prcomp(post_covid_mano, scale = sapply(post_covid_mano,sd))
prop_post <- sum(PCA_post$sdev[1:3])/sum(PCA_post$sdev) # 85.5%
fviz_pca_var(PCA_post,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )
PCA_all <- prcomp(all_data, scale = sapply(all_data,sd))
prop_all <- sum(PCA_all$sdev[1:3])/sum(PCA_all$sdev) # 81.4%
fviz_pca_var(PCA_all,
             col.ind = "cos2", # Color by the quality of representation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE     # Avoid text overlapping
             )

# need to use another PC to get the same level of varability explained when not scaled by sd
```
# extra analysis on the difference between elementary school and high school
```{r}
extra_1516 <- raw_1516 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

extra_1617 <- raw_1617 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

extra_1718 <- raw_1718 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

extra_1819 <- raw_1819 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

extra_2122 <- raw_2122 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

extra_2223 <- raw_2223 %>% 
  select(Student_Attendance_Year_2_Pct,Teacher_Attendance_Year_2_Pct,Suspensions_Per_100_Students_Year_2_Pct,Misconducts_To_Suspensions_Year_2_Pct,Primary_Category) %>%
  na.omit() 

box_pre <- rbind(extra_1516,extra_1617,extra_1718,extra_1819)
box_post <- rbind(extra_2122,extra_2223)


```

#box plot
```{r}
library(gridExtra)

#pre box plot
box_ta_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Teacher_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sa_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Student_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sus_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Suspensions_Per_100_Students_Year_2_Pct)) +
  geom_boxplot() 
box_mis_pre <- ggplot(box_pre, aes(x = Primary_Category, y = Misconducts_To_Suspensions_Year_2_Pct)) +
  geom_boxplot()
grid.arrange(box_ta_pre, box_sa_pre, box_sus_pre, box_mis_pre, ncol = 2, nrow = 2)

#post box plot
box_ta_post <- ggplot(box_post, aes(x = Primary_Category, y = Teacher_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sa_post <- ggplot(box_post, aes(x = Primary_Category, y = Student_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sus_post <- ggplot(box_post, aes(x = Primary_Category, y = Suspensions_Per_100_Students_Year_2_Pct)) +
  geom_boxplot() 
box_mis_post <- ggplot(box_post, aes(x = Primary_Category, y = Misconducts_To_Suspensions_Year_2_Pct)) +
  geom_boxplot()
grid.arrange(box_ta_post, box_sa_post, box_sus_post, box_mis_post, ncol = 2, nrow = 2)

#all box plot
box_ta_all <- ggplot(rbind(box_pre,box_post), aes(x = Primary_Category, y = Teacher_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sa_all <- ggplot(rbind(box_pre,box_post), aes(x = Primary_Category, y = Student_Attendance_Year_2_Pct)) +
  geom_boxplot() 
box_sus_all <- ggplot(rbind(box_pre,box_post), aes(x = Primary_Category, y = Suspensions_Per_100_Students_Year_2_Pct)) +
  geom_boxplot() 
box_mis_all <- ggplot(rbind(box_pre,box_post), aes(x = Primary_Category, y = Misconducts_To_Suspensions_Year_2_Pct)) +
  geom_boxplot()
grid.arrange(box_ta_all, box_sa_all, box_sus_all, box_mis_all, ncol = 2, nrow = 2)
```

